mutation SignIn($input: SigninInput!) {
  signin(input: $input) {
    token
    me {
      id
      email
      roles {
        name
      }
      notificationChecked
      signinData {
        qrCode
        backupCodes
        signinStep
      }
    }
  }
}
